default_model: openai/gpt-5.4
max_loops: 20

models:
  - id: openai/gpt-5.4
    label: GPT-5.4
  - id: synthetic/hf:nvidia/Kimi-K2.5-NVFP4
    label: Kimi K2.5 NVIDIA
  - id: synthetic/hf:moonshotai/Kimi-K2.5
    label: Kimi K2.5
  - id: synthetic/hf:MiniMaxAI/MiniMax-M2.1
    label: MiniMax M2.1
  - id: synthetic/hf:deepseek-ai/DeepSeek-V3.2
    label: DeepSeek V3.2
  - id: opencode/mimo-v2-pro-free
    label: Mimo V2 Pro Free
  - id: modal/zai-org/GLM-5-FP8
    label: GLM-5 FP8
